### ISSUE TITLE
Variables in variables.scss are being ignored.

### ISSUE THREAD

**Issue by mhcdev** [neckerson/slate-bootstrap-theme#11]
Other than the basic $font-* settings all other setting seem to be being ignored and not compiled into the css for the site.

I am not seeing any effect from the following:
$primary:#000;
$brand-primary: #000;
$border-radius:               0;
$border-radius-lg:            0;
$border-radius-sm:            0;
$link-color: #000;
$link-hover-color: #000;
$grid-gutter-width: 20px;

**Comment by neckerson** [comment]
Hey @mhcdev, thanks for bringing this to my attention! I have addressed the issue with variables not being compiled into the CSS with my latest update to the theme. 

Quick note,  some of your variables above seem to be out of date, i.e. ```$border-radius: 0;```, which has been replaced by ```$enable-rounded: false;```. Please see the latest variable definitions here:

https://getbootstrap.com/docs/4.0/getting-started/theming/
