### ISSUE TITLE
Check for JS errors when featured product section is used on homepage

### ISSUE THREAD

**Issue by neckerson** [neckerson/slate-bootstrap-theme#2]
This seems related to selectors used that do not exist in the featured product section when product.js is loaded.

**Comment by Waylon87** [comment]
@neckerson are you referencing the `ReferenceError: $ is not defined` error where its not picking up any jQuery on the home page.

**Comment by neckerson** [comment]
@Waylon87 No, this is / was a separate problem. I'm closing this issue because it's been resolved, please continue the discussion below!

https://github.com/neckerson/slate-bootstrap-theme/issues/6
